2022-02-07 12:41:27,729 INFO    MainThread:31441 [internal.py:wandb_internal():87] W&B internal server running at pid: 31441, started at: 2022-02-07 12:41:27.728970
2022-02-07 12:41:27,739 DEBUG   HandlerThread:31441 [handler.py:handle_request():130] handle_request: check_version
2022-02-07 12:41:27,741 INFO    WriterThread:31441 [datastore.py:open_for_write():77] open: /home/sohui/code/DTC/code/wandb/run-20220207_124125-18h537j3/run-18h537j3.wandb
2022-02-07 12:41:27,753 DEBUG   SenderThread:31441 [sender.py:send():238] send: header
2022-02-07 12:41:27,754 DEBUG   SenderThread:31441 [sender.py:send_request():252] send_request: check_version
2022-02-07 12:41:28,013 DEBUG   SenderThread:31441 [sender.py:send():238] send: run
2022-02-07 12:41:28,447 INFO    SenderThread:31441 [dir_watcher.py:__init__():169] watching files in: /home/sohui/code/DTC/code/wandb/run-20220207_124125-18h537j3/files
2022-02-07 12:41:28,447 INFO    SenderThread:31441 [sender.py:_start_run_threads():825] run started: 18h537j3 with start time 1644237686
2022-02-07 12:41:28,449 DEBUG   SenderThread:31441 [sender.py:send():238] send: summary
2022-02-07 12:41:28,449 INFO    SenderThread:31441 [sender.py:_save_file():960] saving file wandb-summary.json with policy end
2022-02-07 12:41:28,458 DEBUG   HandlerThread:31441 [handler.py:handle_request():130] handle_request: run_start
2022-02-07 12:41:28,473 DEBUG   HandlerThread:31441 [meta.py:__init__():40] meta init
2022-02-07 12:41:28,473 DEBUG   HandlerThread:31441 [meta.py:__init__():54] meta init done
2022-02-07 12:41:28,474 DEBUG   HandlerThread:31441 [meta.py:probe():214] probe
2022-02-07 12:41:28,483 DEBUG   HandlerThread:31441 [git.py:repo():33] git repository is invalid
2022-02-07 12:41:28,484 DEBUG   HandlerThread:31441 [meta.py:_save_pip():58] save pip
2022-02-07 12:41:28,489 DEBUG   HandlerThread:31441 [meta.py:_save_pip():72] save pip done
2022-02-07 12:41:28,490 DEBUG   HandlerThread:31441 [meta.py:_save_conda():79] save conda
2022-02-07 12:41:28,502 ERROR   HandlerThread:31441 [meta.py:_save_conda():88] Error saving conda packages
Traceback (most recent call last):
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/site-packages/wandb/sdk/internal/meta.py", line 84, in _save_conda
    subprocess.call(
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/sohui/anaconda3/envs/unetr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2022-02-07 12:41:28,508 DEBUG   HandlerThread:31441 [meta.py:_save_conda():89] save conda done
2022-02-07 12:41:28,508 DEBUG   HandlerThread:31441 [meta.py:probe():252] probe done
2022-02-07 12:41:28,938 DEBUG   SenderThread:31441 [sender.py:send():238] send: files
2022-02-07 12:41:28,939 INFO    SenderThread:31441 [sender.py:_save_file():960] saving file wandb-metadata.json with policy now
2022-02-07 12:41:28,979 DEBUG   HandlerThread:31441 [handler.py:handle_request():130] handle_request: stop_status
2022-02-07 12:41:28,981 DEBUG   SenderThread:31441 [sender.py:send_request():252] send_request: stop_status
2022-02-07 12:41:29,460 INFO    Thread-13 :31441 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220207_124125-18h537j3/files/requirements.txt
2022-02-07 12:41:29,461 INFO    Thread-13 :31441 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220207_124125-18h537j3/files/wandb-summary.json
2022-02-07 12:41:29,461 INFO    Thread-13 :31441 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220207_124125-18h537j3/files/conda-environment.yaml
2022-02-07 12:41:29,462 INFO    Thread-13 :31441 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220207_124125-18h537j3/files/wandb-metadata.json
2022-02-07 12:41:29,462 INFO    Thread-13 :31441 [dir_watcher.py:_on_file_created():217] file/dir created: /home/sohui/code/DTC/code/wandb/run-20220207_124125-18h537j3/files/output.log
2022-02-07 12:41:29,875 INFO    Thread-16 :31441 [upload_job.py:push():137] Uploaded file /tmp/tmpdwd8k9egwandb/1fbg2u76-wandb-metadata.json
2022-02-07 12:41:31,452 INFO    Thread-13 :31441 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sohui/code/DTC/code/wandb/run-20220207_124125-18h537j3/files/output.log
2022-02-07 12:41:35,457 INFO    Thread-13 :31441 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sohui/code/DTC/code/wandb/run-20220207_124125-18h537j3/files/output.log
2022-02-07 12:41:44,296 DEBUG   HandlerThread:31441 [handler.py:handle_request():130] handle_request: stop_status
2022-02-07 12:41:44,297 DEBUG   SenderThread:31441 [sender.py:send_request():252] send_request: stop_status
2022-02-07 12:41:59,555 DEBUG   HandlerThread:31441 [handler.py:handle_request():130] handle_request: stop_status
2022-02-07 12:41:59,556 DEBUG   SenderThread:31441 [sender.py:send_request():252] send_request: stop_status
2022-02-07 12:42:00,408 DEBUG   SenderThread:31441 [sender.py:send():238] send: stats
2022-02-07 12:42:14,850 DEBUG   HandlerThread:31441 [handler.py:handle_request():130] handle_request: stop_status
2022-02-07 12:42:14,851 DEBUG   SenderThread:31441 [sender.py:send_request():252] send_request: stop_status
2022-02-07 12:42:15,256 WARNING MainThread:31441 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-02-07 12:42:17,513 INFO    Thread-13 :31441 [dir_watcher.py:_on_file_modified():230] file/dir modified: /home/sohui/code/DTC/code/wandb/run-20220207_124125-18h537j3/files/output.log
